services: docker
env:
  global:
    - SQLPG= postgresql://flask_wms:1234@127.0.0.1:5432/wms_api_test
    - PROJECT_PATH=wms-api/

sudo: required
jobs:
  include:
    - stage: test
      language: python
      python: '3.6'
      cache: pip
      services:
        - postgresql
      install:
        # pip install
        - pip install -r requirements.txt
      before_script:
        - cp .env.example .env
        - psql -c "CREATE USER wms_api with CREATEDB PASSWORD '$PGPASS';" -U postgres
        - psql -c 'CREATE DATABASE wms_api_test OWNER wms_api;' -U postgres
        - flask db migrate
        - flask db upgrade heads
      script:
        - pytest -v -ra --color=auto --tb=auto -p no:warnings --cov-report=xml
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
